# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

2.4.6
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.2.4
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/k4/_09nqs851t35bpkk8lr_p43c0000gn/T/build-env

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
Z = np.zeros(10)
print(Z.size * Z.itemsize)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
Z = np.arange(10, 50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
print(np.arange(0, 9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
elements = [1, 2, 0, 0, 4, 0]
print(np.nonzero(elements))


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
print(np.eye(3, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
print(np.random.random((3, 3, 3)))

[[[0.92991032 0.76085755 0.01598034]
  [0.47393359 0.01853061 0.49247741]
  [0.12196977 0.26528758 0.94742908]]

 [[0.17201295 0.65803574 0.32168615]
  [0.3525112  0.00412892 0.57401897]
  [0.70956951 0.14306039 0.30478065]]

 [[0.50264001 0.1920056  0.7573071 ]
  [0.85170113 0.02790191 0.31572263]
  [0.90303531 0.70800596 0.75945552]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [29]:
a = np.random.random((10, 10))
print(a)
print(a.min(), a.max())

[[0.52131767 0.33942531 0.3703175  0.35057384 0.60319278 0.33219738
  0.2436555  0.84218224 0.45883093 0.30724817]
 [0.52240228 0.32780161 0.12390017 0.18753498 0.00234363 0.77916063
  0.51366803 0.66373548 0.42061774 0.64483809]
 [0.81013581 0.59121948 0.8943331  0.079685   0.96640881 0.04860182
  0.19099597 0.80598141 0.05583371 0.77932987]
 [0.88072098 0.95511399 0.87576707 0.67114179 0.75431162 0.74720559
  0.84300556 0.40351419 0.95408326 0.93989384]
 [0.74705034 0.33517273 0.74102476 0.46260665 0.78908408 0.84386879
  0.76911069 0.07014115 0.74502081 0.58807572]
 [0.30336933 0.65330139 0.26818169 0.29869433 0.69613187 0.97405718
  0.51977311 0.2736443  0.86541897 0.93956048]
 [0.06296727 0.60378146 0.54470286 0.45040268 0.44481483 0.18949408
  0.58810875 0.23496538 0.45540809 0.92486848]
 [0.85379537 0.04847374 0.90883083 0.82827183 0.14338876 0.77897118
  0.46059925 0.01410962 0.47142788 0.38581149]
 [0.48729566 0.54502716 0.01621745 0.52706382 0.82605698 0.20904292
  0.5245982 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
a = np.random.random((30))
print(a.mean())

0.583888299889948


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [21]:
b = np.zeros((5, 5)) 
b[0, :] = 1
b[-1, :] = 1
b[:, 0] = 1
b[:, -1] = 1
print(b)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [28]:
a = np.ones((3,3))
a = np.pad(a, 1)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [31]:
0
True
False
0
0
True

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [41]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [55]:
a = np.zeros((8, 8))
a[::2, ::2] = 1
a[1::2, 1::2] = 1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [58]:
print(np.unravel_index(99, (6, 7, 8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [73]:
a = np.tile(([1, 0], [0, 1]), [4, 4])
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [5]:
a = np.random.random((5, 5))
a = (a - a.mean()) / a.std()
print(a)

[[ 0.04868961  1.81056553  1.2632965   0.79431936 -0.72205322]
 [-1.70359395  1.30603442 -0.23359548 -1.4115053  -0.62942712]
 [ 0.25631231  1.22283494 -0.43482356 -0.27787746  0.53873439]
 [ 0.61178728  1.259142    0.52312421 -1.31375711 -1.29980786]
 [-1.42511041 -0.51222347  1.14194794 -0.74264125 -0.07037232]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [10]:
a = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
print(a)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [12]:
print(np.dot(np.random.random((5, 3)), np.random.random((3, 2))))

[[0.73470442 1.20145444]
 [0.65573689 1.05832403]
 [0.7284383  1.08916842]
 [0.78970477 1.19597304]
 [0.71632696 1.01192589]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [32]:
a = np.arange(1, 10)
a[(a >= 3) & (a <= 8)] *= -1
print(a)




[ 1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [4]:
Z = np.arange(1, 6)
1j * Z
Z**Z
2 << Z >> 2
Z/1/1
print(Z <- Z)

[False False False False False]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
nan
0.

[0.]


/var/folders/vh/zm0yk7hx2pvfmznxcj8xwbxw0000gn/T/ipykernel_8767/2027166502.py:1: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [14]:
Z = np.random.uniform(-10, 10, 10)
Y = np.where(Z > 0, np.ceil(Z), np.floor(Z))
print(Y)

[-9. -2.  5. -7. -1.  7.  5. -6. -1. -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [16]:
A = np.random.randint(0, 10, 10)
B = np.random.randint(0, 10, 10)
C = np.intersect1d(A, B)
print(A)
print(B)
print(C)

[2 4 2 7 0 5 8 6 0 3]
[9 1 0 6 3 4 3 8 0 6]
[0 3 4 6 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [17]:
np.seterr(all="ignore")
np.array(0) / np.array(0)

np.float64(nan)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [31]:
print(f"Yesterday: {np.datetime64('today') + np.timedelta64(-1, 'D')}")
print(f"Today: {np.datetime64('today')}") 
print(f"Tomorrow: {np.datetime64('today') + np.timedelta64(1, 'D')}")

Yesterday: 2026-09-11
Today: 2026-09-12
Tomorrow: 2026-09-13


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [33]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
a = np.ones(3)
b = np.ones(3)
np.add(a, b, out=b)
np.negative(a, out=a)
np.divide(a, 2, out=a)
print(np.multiply(b, a, out=a))




[-1. -1. -1.]
[-1. -1. -1.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [84]:
x = np.array([2.7, 5.1])
np.floor(x) # always rounds down 
np.trunc(x) # cuts off the decimals
x.astype(int) # cuts off decimals + the . 
x - x % 1


array([2., 5.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [66]:
z = np.zeros((5, 5))
z = z + np.arange(5)
print(z)



[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [72]:
def generator():
    for i in range(10):
        yield i 

np.fromiter(generator(), dtype=int)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [83]:
a = np.linspace(0, 1, 12)
a = a[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [87]:
np.sort(np.random.random(10))


array([0.04855229, 0.11467067, 0.21151417, 0.34210069, 0.45638702,
       0.61628645, 0.71400224, 0.73323751, 0.85015531, 0.98549188])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [91]:
z = np.arange(10)
np.add.reduce(z)
%timeit np.sum(z)
%timeit np.add.reduce(z)

945 ns ± 52.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
396 ns ± 2.71 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [96]:
a = np.random.random(10)
b = np.random.random(10)
np.allclose(a, b)


False

#### 43. Make an array immutable (read-only) (★★☆)

In [99]:
w = np.arange(3)
w.flags.writeable = False
print(w.flags)
w[0] = 5

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False



ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [104]:
a = np.random.random((10, 2))
print(a)
b = np.zeros((10, 2))
b[:,0] = np.hypot(a[:,0], a[:,1])
b[:,1] = np.arctan2(a[:,1], a[:,0])
print(b)


[[0.62346986 0.90526082]
 [0.98591348 0.29157086]
 [0.72478635 0.20534604]
 [0.48459901 0.80652845]
 [0.84570879 0.30067845]
 [0.17694593 0.44239563]
 [0.56709926 0.25099852]
 [0.87742447 0.28641709]
 [0.65739319 0.15441907]
 [0.66217331 0.69843343]]
[[1.09918689 0.96768205]
 [1.028124   0.28754099]
 [0.75331418 0.27608413]
 [0.94091676 1.02975535]
 [0.89756944 0.34159659]
 [0.4764701  1.19031396]
 [0.62016274 0.41668365]
 [0.92298887 0.31552415]
 [0.67528591 0.23071346]
 [0.96243584 0.81204182]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [109]:
a = np.random.random(10)
a[np.argmax(a)] = 0
print(a)

[0.06115525 0.40625557 0.13716078 0.21845246 0.54380992 0.2789809
 0.33587117 0.56057651 0.50867912 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
a = np.zeros((3, 3), dtype=[('x', 'float'), ('y', 'float')])
a['x'], a['y'] = np.meshgrid(np.linspace(0, 1, 3), np.linspace(1, 0, 3))
print(a)



[[(0. , 1. ) (0.5, 1. ) (1. , 1. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 0. ) (0.5, 0. ) (1. , 0. )]]
[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [120]:
x = np.array([10, 20])
y = np.array([1, 2])
1 / np.subtract.outer(x, y)


array([[0.11111111, 0.125     ],
       [0.05263158, 0.05555556]])

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [137]:
print(f"int16: {np.iinfo(np.int16)}")
print(f"int8: {np.iinfo(np.int8)}")
print(f"int32: {np.iinfo(np.int32)}")
print(f"int64: {np.iinfo(np.int64)}")
print(f"float32: {np.finfo(np.float32)}")
print(f"float64: {np.finfo(np.float64)}")
print(f"float16: {np.finfo(np.float16)}")

int16: Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

int8: Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

int32: Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

int64: Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

float32: Machine parameters for float32
---------------------------------------------------------------
precision = 6   resolution = 1e-06
machep = -23   eps =        1.1920929e-07
negep =  -24   epsneg =    

#### 49. How to print all the values of an array? (★★☆)

In [143]:
import sys
np.set_printoptions(threshold=sys.maxsize)
print(np.arange(2000))

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [150]:
a = np.random.randint(0, 100, 10)
b = a - 50
c = np.abs(b)
print(a)
print(f"closest scalar to 50 = {a[np.argmin(c)]}")

[57 66 64 38 87 94 75 79 31 49]
closest scalar to 50 = 49


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [152]:
d = [('position', [('x', 'float'), ('y', 'float')]), ('colour', [('r', 'uint8'), ('g', 'uint8'), ('b', 'uint8')])]
a = np.zeros(2, dtype=d)
print(a)

[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [190]:
v = np.random.random((100, 2))
x = v[:,0]
y = v[:,1]
xd = np.subtract.outer(x, x)
yd = np.subtract.outer(y, y)
distances = np.hypot(xd, yd)
print(v)
print(x)
print(y)
print(xd)
print(yd)
print(distances)


[[0.63650178 0.49057539]
 [0.37353239 0.09188871]
 [0.37847491 0.10272075]
 [0.58940319 0.37695314]
 [0.58624873 0.7302957 ]
 [0.46492586 0.75892141]
 [0.449686   0.80116709]
 [0.66695994 0.85154005]
 [0.64199765 0.30243482]
 [0.01368634 0.22746837]
 [0.86486555 0.02459391]
 [0.31032151 0.21740356]
 [0.07426978 0.82258512]
 [0.64019305 0.3446228 ]
 [0.47544406 0.28167871]
 [0.45846892 0.54486534]
 [0.92316394 0.81805903]
 [0.85644179 0.90497742]
 [0.95915468 0.45886508]
 [0.98396389 0.70291431]
 [0.14739888 0.62872039]
 [0.37579811 0.59224821]
 [0.34489204 0.83014172]
 [0.33523604 0.2366308 ]
 [0.27305465 0.75648443]
 [0.11601187 0.85124469]
 [0.52527878 0.34810842]
 [0.50670634 0.4691827 ]
 [0.69624112 0.5656957 ]
 [0.18240705 0.23852138]
 [0.43772288 0.47717899]
 [0.94948098 0.9032183 ]
 [0.77080852 0.03838525]
 [0.5574335  0.04521201]
 [0.37156011 0.45081035]
 [0.21763835 0.52932004]
 [0.20436632 0.82843239]
 [0.83168876 0.1030306 ]
 [0.9581948  0.05945539]
 [0.76177861 0.21494085]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [192]:
a = np.array([1.5, 2.7], dtype=np.float32)
b = a.view(np.int32)
b[:] = a
print(b, b.dtype)
print(a)

[1 2] int32
[1.e-45 3.e-45]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5
6, , , 7, 8
, , 9,10,11""") # same commas per row
np.genfromtxt(s, delimiter=",")


array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [210]:
a = np.arange(4).reshape(2, 2)
print(a)
for idx, v in np.ndenumerate(a):
    print(idx, v)


[[0 1]
 [2 3]]
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [226]:
x, y = np.meshgrid(np.linspace(-2, 2, 5), np.linspace(-2, 2, 5))
d = x ** 2 + y ** 2
d2 = -1 * d 
sigma = 1 
gaussian = np.exp(d2 / (2 * sigma ** 2))
print(gaussian)


[[0.01831564 0.082085   0.13533528 0.082085   0.01831564]
 [0.082085   0.36787944 0.60653066 0.36787944 0.082085  ]
 [0.13533528 0.60653066 1.         0.60653066 0.13533528]
 [0.082085   0.36787944 0.60653066 0.36787944 0.082085  ]
 [0.01831564 0.082085   0.13533528 0.082085   0.01831564]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [247]:
a = np.random.choice(6, 2, replace=False)
print(a)
b = np.zeros((2, 3))
np.put(b, a, 1) # indexes goes by row
print(b)



[1 3]
[[0. 1. 0.]
 [1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)